import type { Metadata } from "next";
import "./globals.css";

import Yekan from "@/fonts/yekan";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${Yekan.variable} ${Yekan.className} antialiased flex flex-col items-center relative`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
